### ISSUE TITLE
Package.json: repository field is not present

### ISSUE THREAD

**Issue by Frank3K** [chibat/chrome-extension-typescript-starter#2]
When installing dependencies using npm install the following warning is displayed:

```sh
npm WARN chrome-extension-typescript-starter@1.0.0 No repository field.
```

**Comment by chibat** [comment]
I fixed. https://github.com/chibat/chrome-extension-typescript-starter/commit/d9dbf1a537ea36799e0e928676698a0f1ec13c16
Thanks for your comment !
