### ISSUE TITLE
Webpack doesn't compile all ts files in src folder

### ISSUE THREAD

**Issue by MaskyS** [chibat/chrome-extension-typescript-starter#26]
Hey @chibat, thank you for creating this template, really helps code extensions faster. Today I noticed as I coded up a few more ts files, that they weren't compiled to js. I got it to work by adding more entries in webpack.common.js:

```
module.exports = {
    entry: {
        popup: path.join(__dirname, srcDir + 'popup.ts'),
        options: path.join(__dirname, srcDir + 'options.ts'),
        background: path.join(__dirname, srcDir + 'background.ts'),
        home: path.join(__dirname, srcDir + 'home.ts'), // ! 
        utils: path.join(__dirname, srcDir + 'utils.ts') // !
```

But this seems rather inefficient. How can we direct it to compile all files in the folder without manually specifying each of them?

**Comment by banjo** [comment]
Yeah, I got that issue too. I added a pull request that fixed it!
