### ISSUE TITLE
Why @types/chrome are not picking up by IDE?

### ISSUE THREAD

**Issue by rafis** [chibat/chrome-extension-typescript-starter#3]
NetBeans IDE:
![netbeans](https://user-images.githubusercontent.com/3502395/33976431-d0ece22c-e0a5-11e7-949d-636a3306e24a.png)

When I add the following to the `tsconfig.json` also nothing happens:
```json
        "types": [
            "chrome"
        ],
```

But when I add the following in any of the files it starts to work only after a while, not immediately, why? IDE Bug?
```javascript
/// <reference types="chrome"/>
```
And still showing some error "Project: error: Cannot find type definition file for 'chrome'". But `chrome` object types are now picked up by IDE, I'm happy:
![netbeans2](https://user-images.githubusercontent.com/3502395/33976570-d9e82322-e0a6-11e7-9280-3f1bb2fe21c6.png)

**Comment by MT--** [comment]
This may help: edit `tsconfig.json` to include:
```
"compilerOptions": {
  "typeRoots": [ "node_modules/@types" ]
}
```

What TypeScript version are you using?

**Comment by chibat** [comment]
Sorry for late reply.
I checked with https://github.com/Everlaw/nbts .
I fixed compilerOptions.

Thanks.
