### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Compufreak345** [chibat/chrome-extension-typescript-starter#4]
Hi,

it would be great if you could add a license to your project so I know how it's intended to be used ;)
https://help.github.com/articles/licensing-a-repository/

Thanks & best regards,
Christoph

/Edit: I found a reference to the ISC-license in your package.json - so I assume this is the intended license?

**Comment by chibat** [comment]
I added a MIT license file.
Thaks for the issue.

Best regards,
